FROM postgres:11-alpine

ENV POSTGRES_DB=laravel \
    POSTGRES_USER=phper \
    POSTGRES_PASSWORD=secret \
    POSTGRES_PORT=5432 \
    LANG=ja-JP.utf8

# 省略
# COPY ./my.cnf /etc/my.cnf
# RUN chmod 644 /etc/my.cnf